import type { SkillNode } from './types';

export const SKILL_NODES: SkillNode[] = [
  // ── PUSH TRACK ──────────────────────────────────────────
  {
    id: 'wall-push-up',
    name: 'Wall Push-Up',
    track: 'push',
    level: 0,
    state: 'unlocked',
    prerequisites: [],
    formCues: ['Stand arm-length from wall', 'Keep body rigid', 'Chest touches wall', 'Full elbow extension'],
    strengthStandard: '3×15 clean reps',
    isIsometric: false,
    description: 'Foundation push movement. Builds wrist and shoulder prep.',
  },
  {
    id: 'knee-push-up',
    name: 'Knee Push-Up',
    track: 'push',
    level: 1,
    state: 'locked',
    prerequisites: ['wall-push-up'],
    formCues: ['Hips in line with torso', 'Elbows at 45°', 'Full range of motion', 'Controlled descent'],
    strengthStandard: '3×15 clean reps',
    isIsometric: false,
    description: 'Builds pushing strength with reduced load.',
  },
  {
    id: 'push-up',
    name: 'Push-Up',
    track: 'push',
    level: 2,
    state: 'locked',
    prerequisites: ['knee-push-up'],
    formCues: ['Rigid plank alignment', 'Elbows at 45°', 'Chest to floor', 'Full lockout at top'],
    strengthStandard: '3×15 strict reps',
    isIsometric: false,
    description: 'The foundation of upper-body pushing. Master this before progressing.',
  },
  {
    id: 'diamond-push-up',
    name: 'Diamond Push-Up',
    track: 'push',
    level: 3,
    state: 'locked',
    prerequisites: ['push-up'],
    formCues: ['Hands form diamond shape', 'Elbows track back', 'Keep core tight', 'Chest nearly touches hands'],
    strengthStandard: '3×12 clean reps',
    isIsometric: false,
    description: 'Targets triceps and anterior deltoid intensely.',
  },
  {
    id: 'pike-push-up',
    name: 'Pike Push-Up',
    track: 'push',
    level: 3,
    state: 'locked',
    prerequisites: ['push-up'],
    formCues: ['Hips high in inverted V', 'Head tracks between hands', 'Crown touches floor', 'Drive back to pike'],
    strengthStandard: '3×10 clean reps',
    isIsometric: false,
    description: 'Overhead pressing strength — gateway to handstand push-up.',
  },
  {
    id: 'pseudo-planche-push-up',
    name: 'Pseudo Planche Push-Up',
    track: 'push',
    level: 4,
    state: 'locked',
    prerequisites: ['diamond-push-up', 'pike-push-up'],
    formCues: ['Fingers point backward', 'Lean forward aggressively', 'Elbows flare back', 'Protract scapulae'],
    strengthStandard: '3×10 reps',
    isIsometric: false,
    description: 'Planche-specific pushing strength builder.',
  },
  {
    id: 'archer-push-up',
    name: 'Archer Push-Up',
    track: 'push',
    level: 5,
    state: 'locked',
    prerequisites: ['pseudo-planche-push-up'],
    formCues: ['One arm straight as guide rail', 'One arm does work', 'Rotate torso slightly', 'Full ROM on working arm'],
    strengthStandard: '3×8 each side',
    isIsometric: false,
    description: 'Unilateral pushing — bridge to one-arm push-up.',
  },
  {
    id: 'tuck-planche',
    name: 'Tuck Planche',
    track: 'push',
    level: 6,
    state: 'locked',
    prerequisites: ['archer-push-up'],
    formCues: ['Full scapular protraction', 'Wrists directly under hips', 'Knees tucked to chest', 'Arms locked out'],
    strengthStandard: '10 second hold',
    isIsometric: true,
    description: 'First true planche position — pure pushing strength meets balance.',
  },
  {
    id: 'planche',
    name: 'Full Planche',
    track: 'push',
    level: 7,
    state: 'locked',
    prerequisites: ['tuck-planche'],
    formCues: ['Body parallel to floor', 'Full scapular protraction', 'Core locked rigid', 'Pointed toes'],
    strengthStandard: '5 second hold',
    isIsometric: true,
    description: 'Elite calisthenics skill. Years of dedicated practice.',
  },

  // ── PULL TRACK ──────────────────────────────────────────
  {
    id: 'dead-hang',
    name: 'Dead Hang',
    track: 'pull',
    level: 0,
    state: 'unlocked',
    prerequisites: [],
    formCues: ['Full arm extension', 'Depress scapulae slightly', 'Breathe naturally', 'Grip relaxed but secure'],
    strengthStandard: '60 second hold',
    isIsometric: true,
    description: 'Foundation for all pulling — builds grip and shoulder health.',
  },
  {
    id: 'scapular-pull',
    name: 'Scapular Pull',
    track: 'pull',
    level: 1,
    state: 'locked',
    prerequisites: ['dead-hang'],
    formCues: ['Arms stay straight', 'Only scapulae move', 'Pull shoulder blades down/together', 'Controlled return'],
    strengthStandard: '3×10 reps',
    isIsometric: false,
    description: 'Activates lats without elbow bend — critical pulling foundation.',
  },
  {
    id: 'australian-pull-up',
    name: 'Australian Pull-Up',
    track: 'pull',
    level: 2,
    state: 'locked',
    prerequisites: ['scapular-pull'],
    formCues: ['Body rigid as a plank', 'Pull chest to bar', 'Elbows drive back', 'Squeeze at top'],
    strengthStandard: '3×12 reps',
    isIsometric: false,
    description: 'Horizontal pull — builds back strength for vertical pulling.',
  },
  {
    id: 'pull-up',
    name: 'Pull-Up',
    track: 'pull',
    level: 3,
    state: 'locked',
    prerequisites: ['australian-pull-up'],
    formCues: ['Dead hang start', 'Drive elbows to hips', 'Chin clears bar', 'Controlled lowering'],
    strengthStandard: '3×8 strict reps',
    isIsometric: false,
    description: 'Core vertical pull. Master 10 strict reps before progressing.',
  },
  {
    id: 'chest-to-bar',
    name: 'Chest-to-Bar Pull-Up',
    track: 'pull',
    level: 4,
    state: 'locked',
    prerequisites: ['pull-up'],
    formCues: ['Maintain retracted scapulae', 'Drive chest to bar', 'No kipping', 'Slow eccentric'],
    strengthStandard: '3×6 strict reps',
    isIsometric: false,
    description: 'Higher pull — builds the strength needed for muscle-up.',
  },
  {
    id: 'muscle-up',
    name: 'Muscle-Up',
    track: 'pull',
    level: 5,
    state: 'locked',
    prerequisites: ['chest-to-bar'],
    formCues: ['False grip on bar', 'Pull high and transition early', 'Push to full lockout', 'Control the negative'],
    strengthStandard: '3 strict reps',
    isIsometric: false,
    description: 'The classic gateway skill combining pull and push.',
  },
  {
    id: 'hanging-l-sit',
    name: 'Hanging L-Sit',
    track: 'pull',
    level: 5,
    state: 'locked',
    prerequisites: ['pull-up'],
    formCues: ['Active hanging with scapular engagement', 'Legs parallel to floor', 'Point toes', 'No swinging'],
    strengthStandard: '10 second hold',
    isIsometric: true,
    description: 'Combines pulling and core — prerequisite for back lever.',
  },
  {
    id: 'back-lever',
    name: 'Back Lever',
    track: 'pull',
    level: 6,
    state: 'locked',
    prerequisites: ['muscle-up', 'hanging-l-sit'],
    formCues: ['Start from inverted hang', 'Body parallel below bar', 'Arms straight', 'Squeeze glutes'],
    strengthStandard: '5 second hold',
    isIsometric: true,
    description: 'First hanging lever skill. Demands full-body tension.',
  },
  {
    id: 'front-lever-tuck',
    name: 'Tuck Front Lever',
    track: 'pull',
    level: 7,
    state: 'locked',
    prerequisites: ['back-lever'],
    formCues: ['Knees tucked to chest', 'Hips at bar height', 'Arms straight', 'Depress and retract scapulae'],
    strengthStandard: '10 second hold',
    isIsometric: true,
    description: 'Entry point to the front lever progression.',
  },

  // ── CORE TRACK ──────────────────────────────────────────
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    track: 'core',
    level: 0,
    state: 'unlocked',
    prerequisites: [],
    formCues: ['Lower back pressed to floor', 'Opposite arm/leg extend slowly', 'Exhale through movement', 'No lumbar arch'],
    strengthStandard: '3×10 each side',
    isIsometric: false,
    description: 'Anti-extension core — the true foundation of core training.',
  },
  {
    id: 'hollow-body-hold',
    name: 'Hollow Body Hold',
    track: 'core',
    level: 1,
    state: 'locked',
    prerequisites: ['dead-bug'],
    formCues: ['Lower back flat on floor', 'Arms overhead', 'Legs raised 30°', 'Breathe shallow'],
    strengthStandard: '30 second hold',
    isIsometric: true,
    description: 'The foundational body position for gymnastics and calisthenics.',
  },
  {
    id: 'hollow-body-rock',
    name: 'Hollow Body Rock',
    track: 'core',
    level: 2,
    state: 'locked',
    prerequisites: ['hollow-body-hold'],
    formCues: ['Maintain hollow shape throughout', 'Rock from shoulders to glutes', 'No hip creasing', 'Arms fixed overhead'],
    strengthStandard: '3×15 rocks',
    isIsometric: false,
    description: 'Dynamic hollow body — builds integrated core endurance.',
  },
  {
    id: 'ab-wheel',
    name: 'Ab Wheel Rollout',
    track: 'core',
    level: 3,
    state: 'locked',
    prerequisites: ['hollow-body-rock'],
    formCues: ['Start on knees', 'Roll out slowly', 'Hips stay in line', 'Pull back with lats'],
    strengthStandard: '3×10 full rollouts',
    isIsometric: false,
    description: 'High-intensity anti-extension — builds planche and lever prerequisite strength.',
  },
  {
    id: 'l-sit',
    name: 'L-Sit',
    track: 'core',
    level: 4,
    state: 'locked',
    prerequisites: ['ab-wheel'],
    formCues: ['Hands directly under hips', 'Arms locked out', 'Legs parallel to floor', 'Toes pointed'],
    strengthStandard: '10 second hold',
    isIsometric: true,
    description: 'Pure compression strength — demanding hip flexor and tricep strength.',
  },
  {
    id: 'dragon-flag-tuck',
    name: 'Tuck Dragon Flag',
    track: 'core',
    level: 5,
    state: 'locked',
    prerequisites: ['l-sit'],
    formCues: ['Upper back pinned to bench', 'Knees tucked', 'Lower slowly', 'No touching bench on descent'],
    strengthStandard: '3×8 reps',
    isIsometric: false,
    description: 'Gateway to the full dragon flag — extreme anti-extension.',
  },
  {
    id: 'dragon-flag',
    name: 'Dragon Flag',
    track: 'core',
    level: 6,
    state: 'locked',
    prerequisites: ['dragon-flag-tuck'],
    formCues: ['Body rigid as a plank', 'Shoulders bear weight', 'Lower with control', 'Never touch bench'],
    strengthStandard: '3×5 full reps',
    isIsometric: false,
    description: 'Bruce Lee\'s iconic move. Extreme full-body anti-extension.',
  },
  {
    id: 'front-lever',
    name: 'Full Front Lever',
    track: 'core',
    level: 7,
    state: 'locked',
    prerequisites: ['dragon-flag', 'front-lever-tuck'],
    formCues: ['Body parallel to floor', 'Arms straight', 'Hips in line with shoulders', 'Full posterior chain tension'],
    strengthStandard: '5 second hold',
    isIsometric: true,
    description: 'Elite pulling + core skill. The pinnacle of horizontal pulling strength.',
  },

  // ── LEGS TRACK ──────────────────────────────────────────
  {
    id: 'squat',
    name: 'Bodyweight Squat',
    track: 'legs',
    level: 0,
    state: 'unlocked',
    prerequisites: [],
    formCues: ['Feet shoulder-width apart', 'Knees track over toes', 'Sit to parallel or below', 'Chest upright'],
    strengthStandard: '3×20 reps',
    isIsometric: false,
    description: 'The king of lower body exercises. Build volume here first.',
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    track: 'legs',
    level: 1,
    state: 'locked',
    prerequisites: ['squat'],
    formCues: ['Rear foot elevated', 'Front shin vertical', 'Knee to floor', 'Drive through front heel'],
    strengthStandard: '3×12 each leg',
    isIsometric: false,
    description: 'Unilateral leg strength — exposes imbalances and builds single-leg power.',
  },
  {
    id: 'shrimp-squat-assisted',
    name: 'Assisted Shrimp Squat',
    track: 'legs',
    level: 2,
    state: 'locked',
    prerequisites: ['bulgarian-split-squat'],
    formCues: ['Hold support lightly', 'Back foot held up behind', 'Knee barely touches floor', 'Torso upright'],
    strengthStandard: '3×8 each leg',
    isIsometric: false,
    description: 'Prepares the range of motion for the full shrimp squat.',
  },
  {
    id: 'pistol-squat-assisted',
    name: 'Assisted Pistol Squat',
    track: 'legs',
    level: 2,
    state: 'locked',
    prerequisites: ['bulgarian-split-squat'],
    formCues: ['Hold support lightly', 'One leg extended forward', 'Sit all the way down', 'Drive through heel'],
    strengthStandard: '3×6 each leg',
    isIsometric: false,
    description: 'Teaches the pistol squat pattern with reduced demand.',
  },
  {
    id: 'pistol-squat',
    name: 'Pistol Squat',
    track: 'legs',
    level: 3,
    state: 'locked',
    prerequisites: ['pistol-squat-assisted'],
    formCues: ['No support', 'Full depth — hamstring to calf', 'Extended leg parallel to floor', 'Stand tall at top'],
    strengthStandard: '3×5 each leg unassisted',
    isIsometric: false,
    description: 'The benchmark of single-leg strength and control.',
  },
  {
    id: 'shrimp-squat',
    name: 'Shrimp Squat',
    track: 'legs',
    level: 4,
    state: 'locked',
    prerequisites: ['pistol-squat', 'shrimp-squat-assisted'],
    formCues: ['Back foot held at hip height', 'Deep knee flexion', 'Quad nearly touches floor', 'Upright torso'],
    strengthStandard: '3×5 each leg',
    isIsometric: false,
    description: 'Hardest bodyweight squat variation — extreme quad and hip flexor demand.',
  },
  {
    id: 'nordic-curl',
    name: 'Nordic Curl',
    track: 'legs',
    level: 3,
    state: 'locked',
    prerequisites: ['pistol-squat-assisted'],
    formCues: ['Ankles anchored', 'Body rigid from knees up', 'Lower as slowly as possible', 'Use hands to catch'],
    strengthStandard: '3×5 full reps',
    isIsometric: false,
    description: 'The gold standard for hamstring development and injury prevention.',
  },
  {
    id: 'sissy-squat',
    name: 'Sissy Squat',
    track: 'legs',
    level: 5,
    state: 'locked',
    prerequisites: ['shrimp-squat', 'nordic-curl'],
    formCues: ['Rise onto toes', 'Lean back as knees drop', 'Body from knees to shoulders stays rigid', 'Control descent'],
    strengthStandard: '3×8 reps',
    isIsometric: false,
    description: 'Extreme knee flexion — builds full quad sweep and tendon strength.',
  },
];

export const TRACK_CONFIG: Record<string, { label: string; color: string; emoji: string }> = {
  push: { label: 'Push', color: '#00ff88', emoji: '💪' },
  pull: { label: 'Pull', color: '#00ccff', emoji: '🏋️' },
  core: { label: 'Core', color: '#ff8800', emoji: '🔥' },
  legs: { label: 'Legs', color: '#ff00aa', emoji: '⚡' },
};
